In [25]:
import numpy
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, BatchNormalization, Activation
from keras.layers.convolutional import Conv2D, MaxPooling2D
from keras.constraints import maxnorm
from keras.utils import np_utils

In [26]:
seed = 21

In [27]:
from keras.datasets import cifar10

In [28]:
(X_train, y_train), (X_test, y_test) = cifar10.load_data()

170508288/170498071 [==============================] - 2s 0us/step


In [30]:
print(X_train[0])

[[[ 59  62  63]
  [ 43  46  45]
  [ 50  48  43]
  ...
  [158 132 108]
  [152 125 102]
  [148 124 103]]

 [[ 16  20  20]
  [  0   0   0]
  [ 18   8   0]
  ...
  [123  88  55]
  [119  83  50]
  [122  87  57]]

 [[ 25  24  21]
  [ 16   7   0]
  [ 49  27   8]
  ...
  [118  84  50]
  [120  84  50]
  [109  73  42]]

 ...

 [[208 170  96]
  [201 153  34]
  [198 161  26]
  ...
  [160 133  70]
  [ 56  31   7]
  [ 53  34  20]]

 [[180 139  96]
  [173 123  42]
  [186 144  30]
  ...
  [184 148  94]
  [ 97  62  34]
  [ 83  53  34]]

 [[177 144 116]
  [168 129  94]
  [179 142  87]
  ...
  [216 184 140]
  [151 118  84]
  [123  92  72]]]


In [31]:
X_train = X_train.astype("float32")
X_test = X_test.astype("float32")
X_train = X_train / 255.0
X_test = X_test /255.0

In [32]:
y_train = np_utils.to_categorical(y_train)
y_test = np_utils.to_categorical(y_test)
class_num = y_test.shape[1]

In [33]:
model = Sequential()

In [34]:
model.add(Conv2D(32, (3, 3), input_shape=X_train.shape[1:], padding="same"))
model.add(Activation("relu"))

In [35]:
model.add(Dropout(0.2))

In [36]:
model.add(BatchNormalization())

In [37]:
model.add(Conv2D(64, (3,3), padding = "same"))
model.add(Activation("relu"))

In [38]:
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.2))
model.add(BatchNormalization())

In [39]:
model.add(Conv2D(64, (3,3), padding = "same"))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.2))
model.add(BatchNormalization())

model.add(Conv2D(128, (3,3), padding = "same"))
model.add(Activation("relu"))
model.add(Dropout(0.2))
model.add(BatchNormalization())

In [40]:
model.add(Flatten())
model.add(Dropout(0.2))

In [41]:
model.add(Dense(256, kernel_constraint=maxnorm(3)))
model.add(Activation("relu"))
model.add(Dropout(0.2))
model.add(BatchNormalization())

model.add(Dense(128, kernel_constraint=maxnorm(3)))
model.add(Activation("relu"))
model.add(Dropout(0.2))
model.add(BatchNormalization())

In [42]:
model.add(Dense(class_num))
model.add(Activation("softmax"))

In [49]:
epochs = 25
optimizer = "SGD"

In [50]:
model.compile(loss = "categorical_crossentropy", optimizer = optimizer, metrics=["accuracy"])

In [51]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 32, 32, 32)        896       
                                                                 
 activation (Activation)     (None, 32, 32, 32)        0         
                                                                 
 dropout (Dropout)           (None, 32, 32, 32)        0         
                                                                 
 batch_normalization (BatchN  (None, 32, 32, 32)       128       
 ormalization)                                                   
                                                                 
 conv2d_1 (Conv2D)           (None, 32, 32, 64)        18496     
                                                                 
 activation_1 (Activation)   (None, 32, 32, 64)        0         
                                                        

In [52]:
numpy.random.seed(seed)
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=epochs, batch_size=64)

Epoch 1/25
782/782 [==============================] - 22s 26ms/step - loss: 0.3425 - accuracy: 0.8812 - val_loss: 0.4689 - val_accuracy: 0.8425
Epoch 2/25
782/782 [==============================] - 19s 25ms/step - loss: 0.3207 - accuracy: 0.8900 - val_loss: 0.4841 - val_accuracy: 0.8388
Epoch 3/25
782/782 [==============================] - 19s 25ms/step - loss: 0.3124 - accuracy: 0.8899 - val_loss: 0.4580 - val_accuracy: 0.8499
Epoch 4/25
782/782 [==============================] - 19s 25ms/step - loss: 0.3068 - accuracy: 0.8927 - val_loss: 0.4784 - val_accuracy: 0.8444
Epoch 5/25
782/782 [==============================] - 19s 25ms/step - loss: 0.3012 - accuracy: 0.8957 - val_loss: 0.4665 - val_accuracy: 0.8473
Epoch 6/25
782/782 [==============================] - 19s 24ms/step - loss: 0.2921 - accuracy: 0.8976 - val_loss: 0.8079 - val_accuracy: 0.7380
Epoch 7/25
782/782 [==============================] - 19s 25ms/step - loss: 0.2879 - accuracy: 0.8999 - val_loss: 0.4786 - val_accuracy:

In [53]:
scores = model.evaluate(X_test, y_test, verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))

Accuracy: 85.64%
